import type { LoreEntryV1 } from "./loreRecords.js";

const SOURCE = {
  realm: "https://honkaiimpact3.fandom.com/wiki/Elysian_Realm",
  flameChasers: "https://honkaiimpact3.fandom.com/wiki/Flame-Chasers_(Elysian_Realm)",
  chapter1: "https://honkaiimpact3.fandom.com/wiki/Elysian_Realm/Episodes/Chapter_1",
  chapter2: "https://honkaiimpact3.fandom.com/wiki/Elysian_Realm/Episodes/Chapter_2",
  chapter3: "https://honkaiimpact3.fandom.com/wiki/Elysian_Realm/Episodes/Chapter_3",
  story: "https://honkaiimpact3.fandom.com/wiki/Story",
  chapter31: "https://honkaiimpact3.fandom.com/wiki/Chapter_XXXI",
} as const;

/**
 * Original short summaries distilled from public story references. The game
 * script is deliberately not copied into the package.
 */
export const ELYSIAN_REALM_CANON_VERSION = "1";
export const ELYSIAN_REALM_CANON: readonly LoreEntryV1[] = [
  {
    id: "elysian-setting",
    kind: "setting",
    arcId: "elysian-mainline",
    order: 0,
    title: "往世乐土：由记忆构成的世界",
    summary: "往世乐土是世界蛇地下的记忆空间，保存着前文明逐火之蛾的记忆与经历；后来者通过探索它，沿着先行者的足迹理解对抗崩坏的道路。这里呈现的是记忆模拟，而不是前文明本人本体。",
    cause: "前文明希望把经验、选择和未完成的道路留给未来的继承者。",
    consequence: "进入者可以从交叠而不完整的记忆中寻找答案，并被引向更深处。",
    participants: ["逐火之蛾", "世界蛇", "十三英桀", "雷电芽衣"],
    aliases: ["往世乐土", "Elysian Realm", "记忆空间", "世界蛇地下设施", "前文明"],
    sourceUrl: SOURCE.realm,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "flame-chaser-origin",
    kind: "setting",
    arcId: "elysian-mainline",
    order: 5,
    title: "十三英桀的由来",
    summary: "十三英桀是前文明逐火之蛾的融合战士。在约束之律者带来的灾难后，他们成为少数幸存者，并在共同对抗崩坏的需要下以同一旗帜并肩前行。",
    cause: "前文明的生存危机迫使原本各自承担任务的强者重新联合。",
    consequence: "十三人留下各自的刻印与记忆，成为后继者认识前文明的重要入口。",
    participants: ["十三英桀", "逐火之蛾", "凯文", "爱莉希雅"],
    aliases: ["十三英桀", "逐火十三英桀", "Flame-Chasers", "融合战士", "约束之律者"],
    sourceUrl: SOURCE.flameChasers,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "flame-chaser-roster",
    kind: "character",
    arcId: "elysian-mainline",
    order: 6,
    title: "十三英桀与刻印",
    summary: "十三英桀依次为凯文、爱莉希雅、阿波尼亚、伊甸、维尔薇、千劫、苏、樱、科斯魔、梅比乌斯、格蕾修、华、帕朵菲莉丝；他们留下的刻印分别对应救世、真我、戒律、黄金、螺旋、鏖灭、天慧、刹那、旭光、无限、繁星、浮生与空梦。",
    participants: ["凯文", "爱莉希雅", "阿波尼亚", "伊甸", "维尔薇", "千劫", "苏", "樱", "科斯魔", "梅比乌斯", "格蕾修", "华", "帕朵菲莉丝"],
    aliases: ["英桀排名", "英桀刻印", "救世", "真我", "戒律", "黄金", "螺旋", "鏖灭", "天慧", "刹那", "旭光", "无限", "繁星", "浮生", "空梦"],
    sourceUrl: SOURCE.flameChasers,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "mei-enters-elysian-realm",
    kind: "event",
    arcId: "elysian-mainline",
    order: 10,
    title: "芽衣进入往世乐土",
    summary: "在击败支配之律者后，雷电芽衣获得进入世界蛇地下设施深处的资格，并被凯文引向往世乐土。她以继承者的身份开始探索，希望亲眼查明隐藏在前文明记忆中的答案。",
    cause: "芽衣想追查世界蛇守护的秘密，并寻找关于崩坏意志的线索。",
    consequence: "爱莉希雅在入口迎接她，乐土的探索和英桀试炼由此开始。",
    participants: ["雷电芽衣", "凯文", "爱莉希雅", "世界蛇"],
    aliases: ["芽衣入场", "雷电芽衣", "继承者", "支配之律者", "凯文引路"],
    sourceUrl: SOURCE.chapter1,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "elysian-signets-and-purpose",
    kind: "event",
    arcId: "elysian-mainline",
    order: 20,
    title: "刻印与先行者的足迹",
    summary: "芽衣逐步接触英桀的刻印和个人记忆。爱莉希雅把这些刻印称作灵魂的铭刻与存在的证明，并解释乐土让继承者从先行者的选择中获得继续前进的方向。",
    cause: "英桀需要把各自的道路和经验交给未来，而记忆本身又是破碎、交叠的。",
    consequence: "芽衣开始通过不同英桀的试炼理解他们之间的性格差异、关系和共同目标。",
    participants: ["雷电芽衣", "爱莉希雅", "十三英桀"],
    aliases: ["刻印", "英桀试炼", "记忆碎片", "先行者", "灵魂的铭刻"],
    sourceUrl: SOURCE.chapter1,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "elysian-chapter-one-unity",
    kind: "arc",
    arcId: "elysian-mainline",
    order: 30,
    title: "十三人曾经的联合",
    summary: "在逐火之蛾的危机中，十三英桀意识到只有联合才有可能延续人类。爱莉希雅推动这个群体成为现实，凯文则承担最高的领导位置；然而这份联合最终仍无法改变前文明走向毁灭的结局。",
    cause: "约束之律者之后，分散行动已经不足以应对崩坏。",
    consequence: "十三人的共同旗帜成为乐土要传给后人的核心遗产，也成为他们最深的遗憾。",
    participants: ["爱莉希雅", "凯文", "十三英桀", "逐火之蛾"],
    aliases: ["十三人的联合", "英桀共同体", "前文明覆灭", "共同旗帜", "最深的遗憾"],
    sourceUrl: SOURCE.chapter1,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "elysian-anomalies",
    kind: "event",
    arcId: "elysian-mainline",
    order: 40,
    title: "乐土异常与被隐藏的区域",
    summary: "芽衣以律者身份进入后，乐土的区域、传送门和记忆重构出现异常。负责维护的克莱因发现系统可能遭到人为干预，通往深处的路径也随之改变，调查因此变成了探索的一部分。",
    cause: "律者能量触发了原有防御和系统故障，同时有人借异常遮掩对记忆模拟数据的干预。",
    consequence: "芽衣不再只是在接受试炼，而是必须判断哪些记忆可信、谁在阻止她接近真相。",
    participants: ["雷电芽衣", "克莱因", "爱莉希雅", "渡鸦", "梅比乌斯"],
    aliases: ["乐土异常", "克莱因维护", "记忆重构", "异常区域", "传送门"],
    sourceUrl: SOURCE.chapter2,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "elysian-deep-end",
    kind: "event",
    arcId: "elysian-mainline",
    order: 50,
    title: "通往深处的选择",
    summary: "渡鸦告诉芽衣，乐土深处与解除圣痕持有者的一种限制有关；她因不愿让自己变成非人的怪物而拒绝接受这种力量。芽衣没有停下，而是选择亲自走到深处确认答案。",
    cause: "世界蛇把乐土作为试炼和筛选继承者的设施，深处的力量并非没有代价。",
    consequence: "芽衣决定不接受他人替她判断真相，继续沿着异常打开的路径前进。",
    participants: ["雷电芽衣", "渡鸦", "灰蛇", "凯文", "世界蛇"],
    aliases: ["乐土深处", "深处", "圣痕限制", "渡鸦", "灰蛇", "试炼"],
    sourceUrl: SOURCE.chapter2,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "elysian-aponia-memory-prison",
    kind: "event",
    arcId: "elysian-mainline",
    order: 60,
    title: "阿波尼亚与记忆牢笼",
    summary: "芽衣从帕朵菲莉丝处得到一枚金色吊坠，并因此进入像牢笼一样的记忆空间，见到阿波尼亚。她逐渐察觉阿波尼亚的言语和力量能够影响来访者的意识，也因此更加警惕这段相遇背后的命运。",
    cause: "吊坠成为连接芽衣与隐藏记忆空间的媒介，乐土的异常让原本隔绝的区域相互连通。",
    consequence: "芽衣意识到这里的危险不仅来自敌人，也来自记忆、意志和他人对意识的影响。",
    participants: ["雷电芽衣", "阿波尼亚", "帕朵菲莉丝", "渡鸦"],
    aliases: ["阿波尼亚", "记忆牢笼", "金色吊坠", "帕朵菲莉丝", "意识影响"],
    sourceUrl: SOURCE.chapter3,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "elysian-corruption-truth",
    kind: "event",
    arcId: "elysian-mainline",
    order: 70,
    title: "侵蚀之律者与第十三律者的真相",
    summary: "芽衣继续追查爱莉希雅的记忆时，英桀开始接连消失，线索逐渐指向侵蚀之律者。她与其他英桀借助自己的记忆重建爱莉希雅的记忆副本，最终触及前文明关于第十三律者的最大秘密。",
    cause: "侵蚀之律者正在污染乐土，破坏记忆与英桀之间原本的联系。",
    consequence: "芽衣不再只是旁观前文明，而是成为与英桀共同面对终局、还原真相的继承者。",
    participants: ["雷电芽衣", "爱莉希雅", "十三英桀", "侵蚀之律者"],
    aliases: ["侵蚀之律者", "第十三律者", "爱莉希雅的记忆", "记忆副本", "英桀消失"],
    sourceUrl: SOURCE.story,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
  {
    id: "elysian-final-farewell",
    kind: "event",
    arcId: "elysian-mainline",
    order: 80,
    title: "乐土的终局与告别",
    summary: "在最终旅程中，十三英桀合力阻止侵蚀之律者，往世乐土也随之与其中的侵蚀一同消失。爱莉希雅保护芽衣先行离开，芽衣向英桀和前文明的过去道别，走向只属于继承者的未来。",
    cause: "乐土已经完成保存过去、指引继承者的使命，而侵蚀之律者让继续维持它变得不再可能。",
    consequence: "芽衣带着英桀留下的意志离开；他们不再作为可返回的记忆空间存在，却成为她继续前进的遗产。",
    participants: ["雷电芽衣", "爱莉希雅", "十三英桀", "侵蚀之律者"],
    aliases: ["乐土终局", "爱莉希雅告别", "英桀告别", "Elysium Everlasting", "继承者的未来"],
    sourceUrl: SOURCE.chapter31,
    canonVersion: ELYSIAN_REALM_CANON_VERSION,
  },
];
